/**
 * Dependency graph page (graph.html, generated by build/extras.py).
 *
 * Nodes are results; an edge A -> B means B uses A (solid: @reference, dashed: A's title is
 * mentioned). Layered layout (dagre) flowing top to bottom. Hovering a node highlights
 * everything it builds on and everything that builds on it, and shows a preview; clicking
 * opens the result.
 */

const CYTOSCAPE_URL = 'https://cdn.jsdelivr.net/npm/cytoscape@3.34.3/dist/cytoscape.min.js';
const DAGRE_URL = 'https://cdn.jsdelivr.net/npm/cytoscape-dagre@4.0.1/dist/cytoscape-dagre.js';

function loadScript(src) {
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.onload = resolve;
        script.onerror = () => reject(new Error(`Could not load ${src}`));
        document.head.append(script);
    });
}

const cssVar = name => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
const basePath = () => document.querySelector('meta[name="asset-prefix"]')?.content || './';

function graphStyle() {
    const ink = cssVar('--ink'), paper = cssVar('--paper'),
        accent = cssVar('--accent'), rule = cssVar('--rule-strong');
    return [
        {
            selector: 'node',
            style: {
                'shape': 'round-rectangle',
                'width': 'label', 'height': 'label', 'padding': '9px',
                'background-color': paper,
                'border-width': 1.5, 'border-color': 'data(color)',
                'label': 'data(label)', 'color': ink,
                'font-family': 'STIX Two Text, Times New Roman, serif', 'font-size': 13,
                'text-wrap': 'wrap', 'text-max-width': 170, 'text-valign': 'center', 'text-halign': 'center',
                'transition-property': 'opacity, border-width', 'transition-duration': '150ms',
            },
        },
        { selector: 'node[group = "statements"]', style: { 'border-width': 2.5 } },
        {
            selector: 'edge',
            style: {
                'width': 1.4, 'line-color': rule, 'target-arrow-color': rule,
                'target-arrow-shape': 'triangle', 'arrow-scale': 0.9,
                'curve-style': 'bezier',
                'transition-property': 'opacity, line-color', 'transition-duration': '150ms',
            },
        },
        { selector: 'edge[kind = "mention"]', style: { 'line-style': 'dashed', 'line-dash-pattern': [5, 4] } },
        { selector: '.faded', style: { 'opacity': 0.15 } },
        { selector: 'node.focus', style: { 'border-width': 3.5, 'background-color': cssVar('--hover-wash') || paper } },
        { selector: 'edge.path', style: { 'line-color': accent, 'target-arrow-color': accent, 'width': 2 } },
        { selector: 'node:active, node:selected', style: { 'overlay-opacity': 0 } },
        { selector: '.hidden', style: { 'display': 'none' } },
    ];
}

async function init() {
    const container = document.getElementById('dependency-graph');
    if (!container) return;
    const preview = document.querySelector('.graph-preview');
    const chapterSelect = document.querySelector('.graph-chapter');
    const isolatedToggle = document.querySelector('.graph-isolated');

    let data;
    try {
        [data] = await Promise.all([
            fetch(basePath() + container.dataset.graph, { cache: 'no-cache' }).then(r => r.json()),
            loadScript(CYTOSCAPE_URL).then(() => loadScript(DAGRE_URL)),
        ]);
    } catch (error) {
        container.textContent = `The graph could not be loaded: ${error.message}`;
        container.classList.add('graph-error');
        return;
    }
    window.cytoscape.use(window.cytoscapeDagre);

    const connected = new Set(data.edges.flatMap(e => [e.source, e.target]));
    const chapters = [...new Map(data.nodes.map(n => [n.chapter, n.chapterNumber])).entries()]
        .sort((a, b) => a[1] - b[1]);
    for (const [chapter] of chapters) {
        const option = document.createElement('option');
        option.value = chapter;
        option.textContent = chapter;
        chapterSelect.append(option);
    }

    const cy = window.cytoscape({
        container,
        elements: [
            ...data.nodes.map(n => ({ data: { ...n, label: n.title ? `${n.name}\n${n.title}` : n.name } })),
            ...data.edges.map((e, i) => ({ data: { id: `e${i}`, ...e } })),
        ],
        style: graphStyle(),
        minZoom: 0.2, maxZoom: 2.5, wheelSensitivity: 0.2,
        autoungrabify: true, boxSelectionEnabled: false,
    });

    // Lay out each group of connected results on its own (top to bottom), then pack the
    // groups into rows that fit the frame, largest first. Laying out everything at once puts
    // unrelated groups in one very wide row, which becomes unreadably small when fitted.
    const layout = () => {
        const groups = cy.elements(':visible').components()
            .sort((a, b) => b.nodes().length - a.nodes().length);
        const rowWidth = Math.max(container.clientWidth - 60, 400);
        const gap = 48;
        let x = 0, y = 0, rowHeight = 0;
        for (const group of groups) {
            group.layout({ name: 'dagre', rankDir: 'TB', nodeSep: 22, rankSep: 48, edgeSep: 10, animate: false, fit: false }).run();
            const box = group.boundingBox();
            if (x > 0 && x + box.w > rowWidth) {
                x = 0;
                y += rowHeight + gap;
                rowHeight = 0;
            }
            const dx = x - box.x1, dy = y - box.y1;
            group.nodes().positions(node => ({ x: node.position('x') + dx, y: node.position('y') + dy }));
            x += box.w + gap;
            rowHeight = Math.max(rowHeight, box.h);
        }
        cy.fit(cy.elements(':visible'), 30);
        if (cy.zoom() < 0.85) {  // keep labels readable; the reader can pan
            cy.zoom(0.85);
            const box = cy.elements(':visible').boundingBox();
            cy.pan({ x: 30 - box.x1 * 0.85, y: 30 - box.y1 * 0.85 });
        }
    };

    const applyFilters = () => {
        const chapter = chapterSelect.value;
        const showIsolated = isolatedToggle.checked;
        cy.batch(() => {
            cy.nodes().forEach(node => {
                const visible = (!chapter || node.data('chapter') === chapter)
                    && (showIsolated || connected.has(node.id()));
                node.toggleClass('hidden', !visible);
            });
        });
        layout();
    };
    chapterSelect.addEventListener('change', applyFilters);
    isolatedToggle.addEventListener('change', applyFilters);

    // Hover: highlight what the result builds on and what builds on it
    const shards = new Map();
    const loadShard = shard => {
        if (!shards.has(shard)) {
            shards.set(shard, fetch(`${basePath()}theorems/${shard}.json`, { cache: 'no-cache' })
                .then(r => r.json()).catch(() => ({})));
        }
        return shards.get(shard);
    };

    let hovered = null;
    cy.on('mouseover', 'node', event => {
        const node = event.target;
        hovered = node.id();
        const related = node.predecessors().union(node.successors()).union(node);
        cy.batch(() => {
            cy.elements().addClass('faded');
            related.removeClass('faded');
            related.edges().addClass('path');
            node.addClass('focus');
        });
        container.style.cursor = 'pointer';
        showPreview(node);
    });
    cy.on('mouseout', 'node', () => {
        hovered = null;
        cy.batch(() => cy.elements().removeClass('faded path focus'));
        container.style.cursor = '';
    });
    cy.on('tap', 'node', event => {
        window.location.href = basePath() + event.target.data('url');
    });

    function showPreview(node) {
        const d = node.data();
        const usesCount = node.incomers('node').length, usedByCount = node.outgoers('node').length;
        preview.hidden = false;
        preview.innerHTML = `
            <div class="graph-preview-name"></div>
            <div class="graph-preview-title"></div>
            <div class="graph-preview-body">Loading…</div>
            <div class="graph-preview-meta"></div>`;
        preview.querySelector('.graph-preview-name').textContent = d.name;
        preview.querySelector('.graph-preview-title').textContent = d.title;
        preview.querySelector('.graph-preview-meta').textContent =
            `${d.chapter} · uses ${usesCount} · used by ${usedByCount}`;
        preview.style.setProperty('--env-color', d.color);
        loadShard(d.shard).then(entries => {
            if (hovered !== d.id) return;
            const body = preview.querySelector('.graph-preview-body');
            body.innerHTML = entries[d.id]?.html || '';
            if (window.MathJax?.typesetPromise) MathJax.typesetPromise([body]).catch(() => {});
        });
    }

    // Follow the theme: restyle when the toolbar switches light/dark
    new MutationObserver(() => cy.style(graphStyle())).observe(document.documentElement, {
        attributes: true, attributeFilter: ['data-theme'],
    });

    applyFilters();
    window.addEventListener('resize', () => cy.resize());
}

init();
