// Generated from macros.tex by build/macros.py
window.BOOK_MACROS = {
 "0": "\\mathbf{0}",
 "1": "\\mathbf{1}",
 "A": "\\mathbf{A}",
 "Alt": "\\operatorname{Alt}",
 "B": "\\mathbf{B}",
 "C": "\\mathbf{C}",
 "Cor": "\\operatorname*{Cor}",
 "Corr": "\\operatorname*{Corr}",
 "Cov": "\\operatorname*{Cov}",
 "D": "\\mathbf{D}",
 "E": "\\mathbf{E}",
 "End": "\\operatorname{End}",
 "Ev": "\\operatorname*{\\mathbb{E}}",
 "Exp": [
  "\\mathbb{E}\\left[ #1 \\right]",
  1
 ],
 "F": "\\mathbf{F}",
 "G": "\\mathbf{G}",
 "GL": "\\operatorname{GL}",
 "H": "\\mathbf{H}",
 "Hom": "\\operatorname{Hom}",
 "I": "\\mathbf{I}",
 "J": "\\mathbf{J}",
 "K": "\\mathbf{K}",
 "L": "\\mathbf{L}",
 "M": "\\mathbf{M}",
 "Mat": "\\operatorname{M}",
 "N": "\\mathbf{N}",
 "Normal": [
  "\\mathcal{N}\\left( #1, #2 \\right)",
  2
 ],
 "O": "\\mathbf{O}",
 "Orth": "\\operatorname{O}",
 "P": "\\mathbf{P}",
 "Pr": "\\operatorname{Pr}",
 "Prob": [
  "\\mathbb{P}\\left( #1 \\right)",
  1
 ],
 "Q": "\\mathbf{Q}",
 "R": "\\mathbf{R}",
 "S": "\\mathbf{S}",
 "SL": "\\operatorname{SL}",
 "SO": "\\operatorname{SO}",
 "Sp": "\\operatorname{Sp}",
 "Span": "\\operatorname{span}",
 "Sym": "\\operatorname{Sym}",
 "T": "\\mathbf{T}",
 "U": "\\mathbf{U}",
 "Uniform": [
  "\\text{Uniform}\\left( #1, #2 \\right)",
  2
 ],
 "Unit": "\\operatorname{U}",
 "V": "\\mathbf{V}",
 "Var": "\\operatorname*{Var}",
 "W": "\\mathbf{W}",
 "X": "\\mathbf{X}",
 "Y": "\\mathbf{Y}",
 "Z": "\\mathbf{Z}",
 "a": "\\mathbf{a}",
 "abs": [
  "\\left| #1 \\right|",
  1
 ],
 "adj": "\\operatorname{adj}",
 "b": "\\mathbf{b}",
 "bb": [
  "\\mathbb{#1}",
  1
 ],
 "bm": [
  "\\boldsymbol{#1}",
  1
 ],
 "boundary": [
  "\\partial #1",
  1
 ],
 "bra": [
  "\\langle #1 |",
  1
 ],
 "braket": [
  "\\langle #1 | #2 \\rangle",
  2
 ],
 "c": "\\mathbf{c}",
 "cA": "\\mathcal{A}",
 "cB": "\\mathcal{B}",
 "cC": "\\mathcal{C}",
 "cD": "\\mathcal{D}",
 "cE": "\\mathcal{E}",
 "cF": "\\mathcal{F}",
 "cG": "\\mathcal{G}",
 "cH": "\\mathcal{H}",
 "cI": "\\mathcal{I}",
 "cJ": "\\mathcal{J}",
 "cK": "\\mathcal{K}",
 "cL": "\\mathcal{L}",
 "cM": "\\mathcal{M}",
 "cN": "\\mathcal{N}",
 "cO": "\\mathcal{O}",
 "cP": "\\mathcal{P}",
 "cQ": "\\mathcal{Q}",
 "cR": "\\mathcal{R}",
 "cS": "\\mathcal{S}",
 "cT": "\\mathcal{T}",
 "cU": "\\mathcal{U}",
 "cV": "\\mathcal{V}",
 "cW": "\\mathcal{W}",
 "cX": "\\mathcal{X}",
 "cY": "\\mathcal{Y}",
 "cZ": "\\mathcal{Z}",
 "card": [
  "\\left| #1 \\right|",
  1
 ],
 "charp": "p",
 "cl": [
  "\\mathcal{#1}",
  1
 ],
 "closure": [
  "\\overline{#1}",
  1
 ],
 "codim": "\\operatorname{codim}",
 "col": "\\operatorname{col}",
 "coloneqq": "\\mathrel{:=}",
 "conj": [
  "\\overline{#1}",
  1
 ],
 "conv": "\\operatorname{conv}",
 "coord": [
  "[#1]_{#2}",
  2
 ],
 "d": "\\mathbf{d}",
 "dd": "\\mathrm{d}",
 "defeq": "\\stackrel{\\smash{\\textnormal{\\tiny def}}}{=}",
 "diag": "\\operatorname{diag}",
 "diff": "\\mathop{}\\:\\!\\mathrm d",
 "distBern": "\\operatorname{Ber}",
 "distBeta": "\\operatorname{Beta}",
 "distBin": "\\operatorname{Bin}",
 "distCauchy": "\\operatorname{Cauchy}",
 "distDir": "\\operatorname{Dir}",
 "distExp": "\\operatorname{Exp}",
 "distGamma": "\\operatorname{Gamma}",
 "distGeom": "\\operatorname{Geo}",
 "distHyp": "\\operatorname{Hyp}",
 "distInvWishart": "\\operatorname{InvWishart}",
 "distLognormal": "\\operatorname{Lognormal}",
 "distMult": "\\operatorname{Mult}",
 "distN": "\\operatorname{\\mathcal{N}}",
 "distNB": "\\operatorname{NB}",
 "distPareto": "\\operatorname{Pareto}",
 "distPois": "\\operatorname{Poi}",
 "distUnif": "\\operatorname{Unif}",
 "distWeibull": "\\operatorname{Weibull}",
 "distWishart": "\\operatorname{Wishart}",
 "e": "\\mathbf{e}",
 "eqqcolon": "\\mathrel{=:}",
 "ev": "\\operatorname{ev}",
 "expect": [
  "\\langle #1 \\rangle",
  1
 ],
 "f": "\\mathbf{f}",
 "g": "\\mathbf{g}",
 "h": "\\mathbf{h}",
 "hc": "^{*}",
 "i": "\\mathbf{i}",
 "id": "\\operatorname{id}",
 "im": "\\operatorname{im}",
 "img": "\\operatorname{img}",
 "inner": [
  "\\langle #1, #2 \\rangle",
  2
 ],
 "interior": [
  "\\text{int}\\left( #1 \\right)",
  1
 ],
 "ip": [
  "\\langle#1,#2\\rangle",
  2
 ],
 "j": "\\mathbf{j}",
 "k": "\\mathbf{k}",
 "ker": "\\operatorname{ker}",
 "ket": [
  "| #1 \\rangle",
  1
 ],
 "ketbra": [
  "| #1 \\rangle\\langle #2 |",
  2
 ],
 "l": "\\mathbf{l}",
 "limi": [
  "\\lim_{#1 \\to \\infty}",
  1
 ],
 "limz": [
  "\\lim_{#1 \\to 0}",
  1
 ],
 "m": "\\mathbf{m}",
 "mtx": [
  "[#1]_{#2}^{#3}",
  3
 ],
 "n": "\\mathbf{n}",
 "nA": "\\mathbb{A}",
 "nB": "\\mathbb{B}",
 "nC": "\\mathbb{C}",
 "nD": "\\mathbb{D}",
 "nE": "\\mathbb{E}",
 "nF": "\\mathbb{F}",
 "nG": "\\mathbb{G}",
 "nH": "\\mathbb{H}",
 "nI": "\\mathbb{I}",
 "nJ": "\\mathbb{J}",
 "nK": "\\mathbb{K}",
 "nL": "\\mathbb{L}",
 "nM": "\\mathbb{M}",
 "nN": "\\mathbb{N}",
 "nO": "\\mathbb{O}",
 "nP": "\\mathbb{P}",
 "nQ": "\\mathbb{Q}",
 "nR": "\\mathbb{R}",
 "nS": "\\mathbb{S}",
 "nT": "\\mathbb{T}",
 "nU": "\\mathbb{U}",
 "nV": "\\mathbb{V}",
 "nW": "\\mathbb{W}",
 "nX": "\\mathbb{X}",
 "nY": "\\mathbb{Y}",
 "nZ": "\\mathbb{Z}",
 "norm": [
  "\\left\\| #1 \\right\\|",
  1
 ],
 "nul": "\\operatorname{nul}",
 "nullity": "\\operatorname{nullity}",
 "o": "\\mathbf{o}",
 "p": "\\mathbf{p}",
 "pd": [
  "\\frac{\\partial #1}{\\partial #2}",
  2
 ],
 "pdd": [
  "\\frac{\\partial^2 #1}{\\partial #2^2}",
  2
 ],
 "powerset": [
  "\\mathcal{P}\\left( #1 \\right)",
  1
 ],
 "q": "\\mathbf{q}",
 "r": "\\mathbf{r}",
 "rank": "\\operatorname{rank}",
 "rom": [
  "\\mathrm{#1}",
  1
 ],
 "row": "\\operatorname{row}",
 "s": "\\mathbf{s}",
 "sA": "\\mathcal{A}",
 "sB": "\\mathcal{B}",
 "sC": "\\mathcal{C}",
 "sD": "\\mathcal{D}",
 "sE": "\\mathcal{E}",
 "sF": "\\mathcal{F}",
 "sG": "\\mathcal{G}",
 "sH": "\\mathcal{H}",
 "sI": "\\mathcal{I}",
 "sJ": "\\mathcal{J}",
 "sK": "\\mathcal{K}",
 "sL": "\\mathcal{L}",
 "sM": "\\mathcal{M}",
 "sN": "\\mathcal{N}",
 "sO": "\\mathcal{O}",
 "sP": "\\mathcal{P}",
 "sQ": "\\mathcal{Q}",
 "sR": "\\mathcal{R}",
 "sS": "\\mathcal{S}",
 "sT": "\\mathcal{T}",
 "sU": "\\mathcal{U}",
 "sV": "\\mathcal{V}",
 "sW": "\\mathcal{W}",
 "sX": "\\mathcal{X}",
 "sY": "\\mathcal{Y}",
 "sZ": "\\mathcal{Z}",
 "sgn": "\\operatorname{sgn}",
 "spec": "\\operatorname{spec}",
 "spn": "\\operatorname{span}",
 "t": "\\mathbf{t}",
 "td": [
  "\\frac{d #1}{d #2}",
  2
 ],
 "tdd": [
  "\\frac{d^2 #1}{d #2^2}",
  2
 ],
 "tp": "^{\\top}",
 "tr": "\\operatorname{tr}",
 "u": "\\mathbf{u}",
 "uinorm": [
  "\\left|\\!\\left|\\!\\left| #1 \\right|\\!\\right|\\!\\right|",
  1
 ],
 "v": "\\mathbf{v}",
 "vDelta": "\\bm{\\Delta}",
 "vGamma": "\\bm{\\Gamma}",
 "vLambda": "\\bm{\\Lambda}",
 "vOmega": "\\bm{\\Omega}",
 "vPhi": "\\bm{\\Phi}",
 "vPi": "\\bm{\\Pi}",
 "vPsi": "\\bm{\\Psi}",
 "vSigma": "\\bm{\\Sigma}",
 "vTheta": "\\bm{\\Theta}",
 "vUpsilon": "\\bm{\\Upsilon}",
 "vXi": "\\bm{\\Xi}",
 "valpha": "\\bm{\\upalpha}",
 "vbeta": "\\bm{\\upbeta}",
 "vchi": "\\bm{\\upchi}",
 "vdelta": "\\bm{\\updelta}",
 "vecop": "\\operatorname{vec}",
 "vepsilon": "\\bm{\\upepsilon}",
 "veta": "\\bm{\\upeta}",
 "vgamma": "\\bm{\\upgamma}",
 "viota": "\\bm{\\upiota}",
 "vkappa": "\\bm{\\upkappa}",
 "vlambda": "\\bm{\\uplambda}",
 "vmu": "\\bm{\\upmu}",
 "vnu": "\\bm{\\upnu}",
 "vol": "\\operatorname{vol}",
 "vomega": "\\bm{\\upomega}",
 "vphi": "\\bm{\\upphi}",
 "vpi": "\\bm{\\uppi}",
 "vpsi": "\\bm{\\uppsi}",
 "vrho": "\\bm{\\uprho}",
 "vsigma": "\\bm{\\upsigma}",
 "vtau": "\\bm{\\uptau}",
 "vtheta": "\\bm{\\uptheta}",
 "vupsilon": "\\bm{\\upupsilon}",
 "vvarepsilon": "\\bm{\\upvarepsilon}",
 "vvarphi": "\\bm{\\upvarphi}",
 "vvarpi": "\\bm{\\upvarpi}",
 "vvarrho": "\\bm{\\upvarrho}",
 "vvarsigma": "\\bm{\\upvarsigma}",
 "vvartheta": "\\bm{\\upvartheta}",
 "vxi": "\\bm{\\upxi}",
 "vzeta": "\\bm{\\upzeta}",
 "w": "\\mathbf{w}",
 "x": "\\mathbf{x}",
 "y": "\\mathbf{y}",
 "z": "\\mathbf{z}"
};
